name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get AF playlist
        run: ./wbs_get_json.sh 44c831zcVMnzLHIatXe4N4 > playlist.json
      - name: get franssen playlist
        run: ./wbs_get_json.sh 44LsKI7378Wl34it2kaK7b > playlist_franssen.json
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
